# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IR', '0002_auto_20170303_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
