# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IR', '0004_auto_20170303_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='length',
            field=models.IntegerField(default=1),
        ),
    ]
